// tab切换
export const TAB_CHANGE = 'TAB_CHANGE';
export const TAB_CHANGE_SUCCESS = 'TAB_CHANGE_SUCCESS';
export const TAB_CHANGE_ERROR = 'TAB_CHANGE_ERROR';

// 获取主题列表
export const GET_TOPIC_LIST = 'GET_TOPIC_LIST';
export const GET_TOPIC_LIST_SUCCESS = 'GET_TOPIC_LIST_SUCCESS';
export const GET_TOPIC_LIST_ERROR = 'GET_TOPIC_LIST_ERROR';

// 获取主题详情
export const GET_TOPIC_DETAIL = 'GET_TOPIC_DETAIL';
export const GET_TOPIC_DETAIL_SUCCESS = 'GET_TOPIC_DETAIL_SUCCESS';
export const GET_TOPIC_DETAIL_ERROR = 'GET_TOPIC_DETAIL_ERROR';

// 检查用户accesstoken
export const CHECK_ACCESS_TOKEN = 'CHECK_ACCESS_TOKEN';
export const CHECK_ACCESS_TOKEN_SUCCESS = 'CHECK_ACCESS_TOKEN_SUCCESS';
export const CHECK_ACCESS_TOKEN_ERROR = 'CHECK_ACCESS_TOKEN_ERROR';

// 设置用户accesstoken
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_ACCESS_TOKEN_SUCCESS = 'SET_ACCESS_TOKEN_SUCCESS';
export const SET_ACCESS_TOKEN_ERROR = 'SET_ACCESS_TOKEN_ERROR';

// 添加收藏
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_ERROR = 'ADD_COLLECTION_ERROR';

// 取消收藏
export const DEL_COLLECTION = 'DEL_COLLECTION';
export const DEL_COLLECTION_SUCCESS = 'DEL_COLLECTION_SUCCESS';
export const DEL_COLLECTION_ERROR = 'DEL_COLLECTION_ERROR';

// 获取作者信息
export const GET_AUTHOR = 'GET_AUTHOR';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_AUTHOR_ERROR = 'GET_AUTHOR_ERROR';

// Flux -> redux -> redux-thunk -> redux-saga -> mobx
